/* eslint-disable no-undef */
/// <reference types="cypress" />

context('Actions', () => {
  beforeEach(() => {
    cy.visit('http://localhost:3000/?handle=&body=&replies=&date=&time=&retweets=0&likes=0&profilePic=&platform=')
  })

  it('should type into the form, submit, and clear inputs, and display tweet', () => {
    cy.get('.thandle')
      .type('poonicorn').should('have.value', 'poonicorn')
    cy.get('.tbody')
      .type('this is a tweet').should('have.value', 'this is a tweet')
    cy.get('.treplies')
      .type('4').should('have.value', '4')
    cy.get('.tdate')
      .type('2020-12-25').should('have.value', '2020-12-25')
    cy.get('.ttime')
      .type('11:59').should('have.value', '11:59')
    cy.get('.tretweets')
      .type('17').should('have.value', '17')
    cy.get('.tlikes')
      .type('21').should('have.value', '21')
    cy.get('.tprofile-pic')
      .type('urlfortheprofilepic.jpg').should('have.value', 'urlfortheprofilepic.jpg')
    cy.get('.tplatform')
      .type('twitter for android').should('have.value', 'twitter for android')
    cy.get('.tsubmit')
      .click()

    cy.get('.thandle')
      .should('have.value', '')
    cy.get('.tbody')
      .should('have.value', '')
    cy.get('.treplies')
      .should('have.value', '')
    cy.get('.tdate')
      .should('have.value', '')
    cy.get('.ttime')
      .should('have.value', '')
    cy.get('.tretweets')
      .should('have.value', '')
    cy.get('.tlikes')
      .should('have.value', '')
    cy.get('.tprofile-pic')
      .should('have.value', '')

    cy.get('.nhandle')
      .contains('poonicorn')
    cy.get('.nbody')
      .contains('this is a tweet')
    cy.get('.nreplies')
      .contains('4')
    cy.get('.ndate')
      .contains('2020-12-25')
    cy.get('.ntime')
      .contains('11:59')
    cy.get('.nretweets')
      .contains('17')
    cy.get('.nlikes')
      .contains('21')
    cy.get('.nprofile-pic')
      .contains('urlfortheprofilepic.jpg')
    cy.get('.nplatform')
      .contains('twitter for android')
  })
})
